### BC 카드 소비 데이터 분석
#### 2026.04.23_김근하 작성

### 1. 데이터 로딩 및 확인  
#### ● 데이터 확인 : 앞부분, 뒷부분, 데이터수 (bccard_201906.csv)

In [ ]:
import pandas as pd  #판다스 함수 연결

#분석용 데이터 불러오기 (bccard_201906.csv)
filename = './bccard_201906.csv' 
bccard = pd.read_csv(filename) 
bccard

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892
1,1,201906,11,서울특별시,1159,동작구,11590560,상도4동,30,생활,...,내국인,11,서울특별시,1165,서초구,2,20대,1,109290,18
2,2,201906,11,서울특별시,1162,관악구,11620595,청룡동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,20대,1,268850,52
3,3,201906,11,서울특별시,1144,마포구,11440660,서교동,80,음식,...,내국인,11,서울특별시,1138,은평구,1,20대,1,44174450,1790
4,4,201906,11,서울특별시,1120,성동구,11200550,사근동,80,음식,...,내국인,11,서울특별시,1120,성동구,1,20대,1,60338146,3536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99996,99996,201906,11,서울특별시,1165,서초구,11650520,서초2동,30,생활,...,내국인,43,충청북도,4311,청주시,1,50대,4,50600,10
99997,99997,201906,11,서울특별시,1117,용산구,11170520,용산2가동,30,생활,...,내국인,11,서울특별시,1162,관악구,1,40대,2,38640,7
99998,99998,201906,11,서울특별시,1156,영등포구,11560535,영등포동,30,생활,...,내국인,28,인천광역시,2817,미추홀구,2,30대,2,340590,15
99999,99999,201906,11,서울특별시,1141,서대문구,11410585,신촌동,40,쇼핑,...,내국인,44,충청남도,4413,천안시,1,20대,2,117100,3
100000,100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

#### 데이터 앞부분

In [ ]:
bccard_df.head(1) # 데이터 앞부분 추출

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
0,0,201906,11,서울특별시,1162,관악구,11620585,낙성대동,80,음식,...,내국인,11,서울특별시,1162,관악구,2,30대,2,26284804,1892

#### 데이터 뒷부분

In [ ]:
bccard_df.tail(1) #데이터 뒷부분 추출

,Unnamed: 0,REG_YYMM,MEGA_CTY_NO,MEGA_CTY_NM,CTY_RGN_NO,CTY_RGN_NM,ADMI_CTY_NO,ADMI_CTY_NM,MAIN_BUZ_CODE,MAIN_BUZ_DESC,...,CSTMR_GUBUN,CSTMR_MEGA_CTY_NO,CSTMR_MEGA_CTY_NM,CSTMR_CTY_RGN_NO,CSTMR_CTY_RGN_NM,SEX_CTGO_CD,AGE_VAL,FLC,AMT,CNT
100000,100000,201906,11,서울특별시,1135,노원구,11350710,상계9동,20,문화,...,내국인,41,경기도,4115,의정부시,1,40대,3,5227500,7

#### 데이터 수

In [ ]:
len(bccard_df) #len 을 씌워서 데이터 수량 정리

100001

### 2. 서울시 거주/비거주 고객 비교 분석
#### 2-1.고객수, 총 소비액, 카드 이용 건수

In [ ]:

bccard_df = pd.DataFrame(bccard)
A=len(bccard_df[bccard_df.CSTMR_MEGA_CTY_NM == '서울특별시']) #고객 수를 len 으로 서울 시 거주 조건은 boolean 안덱스 조건 식으로 요청
B=len(bccard_df[bccard_df.CSTMR_MEGA_CTY_NM != '서울특별시']) #고객 수를 len 으로 서울 시 비 거주 조건은 boolean 안덱스 조건 식으로 요청
print(f'서울시 거주:{A},서울시 外 거주:{B}')

서울시 거주:54150,서울시 外 거주:45851

#### 총 소비액

In [ ]:
bccard_df = pd.DataFrame(bccard)
A=bccard_df[bccard_df.CSTMR_MEGA_CTY_NM == '서울특별시']['AMT'].sum() #총 합을 Sum 으로, 서울 시 거주 조건은 boolean 안덱스 조건 식으로, 소비액은 AMT로 요청
B=bccard_df[bccard_df.CSTMR_MEGA_CTY_NM != '서울특별시']['AMT'].sum() #총 합을 Sum 으로, 서울 시  미 거주 조건은 boolean 안덱스 조건 식으로, 소비액은 AMT로 요청
print(A,B)

119663142676 146587135822

#### 카드 이용 건 수

In [ ]:
bccard_df = pd.DataFrame(bccard)
A=bccard_df[bccard_df.CSTMR_MEGA_CTY_NM == '서울특별시']['CNT'].sum() # 위 사항과 거의 동등 하되 카드 이용 건 수는 CNT로 표현
B=bccard_df[bccard_df.CSTMR_MEGA_CTY_NM != '서울특별시']['CNT'].sum() # 위 사항과 거의 동등 하되 카드 이용 건 수는 CNT로 표현
print(A,B)

5542462 4950200

#### 행렬 표시

In [49]:
bccard_dict = { '서울시' : ['거주', '비거주'],
              '고객수'  : [54150, 45851],
              '총 소비액' : [119663142676, 146587135822],  
              '카드 이용 건 수' : [5542462, 4950200]  


}
bccard_df = pd.DataFrame(bccard_dict)
bccard_df

   서울시    고객수         총 소비액  카드 이용 건 수
0   거주  54150  119663142676    5542462
1  비거주  45851  146587135822    4950200

### 3.편의점 소비 정보 분석

In [50]:
bccard_df = pd.DataFrame(bccard)
C=bccard_df[bccard_df.TP_BUZ_NO == 4010]['AMT'].sum()
D=bccard_df[bccard_df.MEGA_CTY_NM == '서울특별시']['AMT'].sum()
print(f'편의점 소비액:{C}, 서울시 소비액:{D}')

편의점 소비액:7299184098, 서울시 소비액:266250278498

#### 3-1. 편의점 소비액, 강남구 소비액

In [51]:
add_D=bccard_df[(bccard_df.CTY_RGN_NM == '강남구') & (bccard_df.TP_BUZ_NO == 4010)]['AMT'].sum()
print(f'강남구 편의점 소비액:{add_D}')

강남구 편의점 소비액:707275140

#### 3-2. 강남구 편의점 소비액

In [52]:
E=bccard_df[(bccard_df.CTY_RGN_NM == '강남구') & (bccard_df.TP_BUZ_NO == 4010) & (bccard_df.CSTMR_CTY_RGN_NM == '강남구')]['AMT'].sum()
F=bccard_df[(bccard_df.CTY_RGN_NM == '강남구') & (bccard_df.TP_BUZ_NO == 4010) & (bccard_df.CSTMR_CTY_RGN_NM != '강남구')]['AMT'].sum()
E, F

(np.int64(288379890), np.int64(418895250))

#### 3-3. 강남구 편의점 소비액 중 강남구 거주자와 비거주자의 소비액 비교 행렬 표시

In [48]:
bccard_dict = { '강남구 편의점' : ['소비액'],
                '강남구 거주' : [288379890],
                '강남구 비 거주' : [418895250],
                '강남구 편의점 총 소비액' : [707275140]
}
bccard_df = pd.DataFrame(bccard_dict)
bccard_df

  강남구 편의점     강남구 거주   강남구 비 거주  강남구 편의점 총 소비액
0     소비액  288379890  418895250      707275140